### ISSUE TITLE
[Problem] ClassNotFoundException for class Wrapper1_20_R3

### ISSUE THREAD

**Issue by steffqxyz** [Rapha149/SignGUI#12]
### API version

2.3.2

### Server software and version

1.20.4 Paper

### What are you trying to do?

I want to get text input from a sign so players deposit and withdraw money easier in my banking system

### What do you need help with?

I get a ClassNotFoundException when trying to use the SignGUI for the Wrapper1_20_R3 class in module 1_20_R3.

I tried shading it, but I am not that experienced with shading in gradle. 

https://pastes.dev/CK2y60Fp7D -- here is the error

### Code snippets

```

shadowJar {
    // minimizes the libraries to only include classes you actually used
    minimize()

    // shade the signgui library
    dependencies {
        include(dependency("de.rapha149.signgui:signgui:2.3.2"))
        include(dependency("com.github.kangarko:Foundation:6.7.14"))
    }
}

assemble.dependsOn(shadowJar)
```

```
implementation("de.rapha149.signgui:signgui:2.3.2")
```

### Any additional comments?

I am using JAVA 17

**Comment by Rapha149** [comment]
Does the class file show up when you open your plugin's jar file using a zip program like 7zip or WinRAR?

And you could also try if it works if you add this statement **before** ever using the SignGUI:
```java
Class.forName("de.rapha149.signgui.version.Wrapper1_20_R3");
```

If that also does not work, try to use this:
```java
Class.forName("de.rapha149.signgui.version.Wrapper1_20_R3", true, getClassLoader());

// or if you don't do this in your plugin's main class,
// replace PLUGIN_INSTANCE with the instance of your main class:
Class.forName("de.rapha149.signgui.version.Wrapper1_20_R3", true, PLUGIN_INSTANCE.getClassLoader());
```

**Comment by steffqxyz** [comment]
Sorry for the late response, I get a class not found error after trying that in the onEnable method, the class is not in the jar file if I open it with winrar.

**Comment by Rapha149** [comment]
Ok, I looked at your Gradle snippet again right now and noticed the description of `minimize()` which apparently removes all classes not needed. My guess is that that is causing the wrapper class not being compiled because in my API the specific wrapper class for the Spigot version is loaded via Reflection and the code behind `minimize` doesn't detect the wrapper classes as needed because of that.

Now if I'm right about that you have to options:
1. Remove the `minimize()` statement, but will also cause the compilation of other classes that are actually unnecessary.
2. Add a `new Wrapper1_20_R3()` statement somewhere in your code, probably best in the `onEnable` method so that Gradle detects the class as needed. I'm not 100% sure that this option would work but it could be worth a try. And if you change Minecraft versions sometime you obviously have to amend that statement to load a different wrapper class.

**Comment by steffqxyz** [comment]
2nd one worked, thanks! Have a great day

**Comment by steffqxyz** [comment]
I got a question actually, I need to get input from what a player types but if I do something like this, the number ends up being 0
```
SignGUI gui = SignGUI.builder()
                    .setType(CompMaterial.OAK_SIGN.getMaterial())
                    .setHandler((p, result) -> {
                        String line = result.getLine(0);
                        if (line.isEmpty())
                            return List.of();
                        amountToDeposit = Integer.parseInt(line);
                        return Collections.emptyList();
                    }).build();

            player.closeInventory();

            gui.open(player);
 ```

**Comment by Rapha149** [comment]
Well that code looks correct - if you want the number to be entered on the first line of the sign. My guess would be that the error is outside of that code snippet, but I'm going to need more context than that. For example: whereis `amountToDeposit` defined, when do you read its value after the player closed the sign, you said you get the output `0` but where do you get that? In the code snippet you sent there isn't any code that outputs the value of `amountToDeposit` etc.

Another thing off-topic: `List.of()` and `Collections.emptyList()` do the same thing: they return an empty `java.util.List` which in the case of my API means that the sign should be closed without further action.

**Comment by Rapha149** [comment]
I see the mistake you made. The method `gui.open(player);` returns immediately, it does not wait until the sign is closed. Therefore the code below that method is also executed while the sign is still open - and the variable is therefore still `0`.
What you should do instead is put code below the open method inside the `setHandler` method like this:
```java
SignGUI gui = SignGUI.builder()
        .setType(CompMaterial.OAK_SIGN.getMaterial())
        .setHandler((p, result) -> {
            String line = result.getLine(1);
            if (line.isEmpty())
                return List.of(SignGUIAction.displayNewLines(null, "Please enter a", "valid amount!"));
                
            int amountToWithdraw = Integer.parseInt(line);
            if (playerSettingsFile.getBalance() < amountToWithdraw) {
                Common.tell(player, Messages.BANK_WITHDRAW_FAILED);
                return Collections.emptyList();
            }
            
            playerSettingsFile.setBalance(playerSettingsFile.getBalance() + amountToWithdraw);
            playerSettingsFile.setBankBalance(bankBalance - amountToWithdraw);
            Common.tell(player, Messages.BANK_WITHDRAW.replace("{amount}", String.valueOf(amountToWithdraw)));
            return Collections.emptyList();
        }).build();

player.closeInventory();
gui.open(player);
```

(btw, I also split your string `"Please enter a valid amount!"` into two lines because that whole string will never fit into one line and I added a `null` line before that so the first line of the sign is empty and the player knows where to enter the amount)

**Comment by steffqxyz** [comment]
It worked, thank you so much!

**Comment by Rapha149** [comment]
You're welcome :)
