### ISSUE TITLE
[Bug] Players can modify the pre-written lines in the sign

### ISSUE THREAD

**Issue by Dqmino** [Rapha149/SignGUI#18]
### API version

2.3.6

### Server software and version

Spigot 1.20.4

### Steps to reproduce

```bash
1. create a sign gui
2. set lines programmatically
3. delete the lines in your minecraft client
```

### Expected behaviour

Players can only delete what they have written

### What is actually happening?

Players can freely delete anything in the sign, even pre written lines

**Comment by Dqmino** [comment]
If this is intended, then is it possible to disable it?

**Comment by Rapha149** [comment]
This is due to the nature of sign editing in Minecraft and cannot be changed without the use of mods.
When I use the API, I simply ignore the lines that I have pre-written and take the player's response from the previously empty lines. This way, the pre-written lines serve as a display on what information the player should write but it doesn't matter if the player deletes or changes these lines.
